NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
#str(NEI)
#unique(NEI$type)
#unique(NEI$year)
typ = unique(NEI$type)
yrs = unique(NEI$year)
NEI$year = factor(NEI$year,levels=yrs)
NEI$type = factor(NEI$type,levels=typ)
#str(NEI)
scc = unique(NEI$SCC)
#head(scc)
NEI$SCC = factor(NEI$SCC,levels=scc)
#length(scc)
fp = unique(NEI$fips)
#length(fp)
NEI$fips = factor(NEI$fips,levels=fp)
#str(NEI)
total = aggregate(Emissions~year,data=NEI,FUN=sum)
total[[2]] = total[[2]]/1000

barplot(total[[2]],names.arg=total[[1]],main="Total PM2.5 emission (year-wise)",ylab="PM2.5 Emissions in kilo tons",xlab="Years",col = c("red","green","blue","gray"))
dev.copy(png,'plot1.png')
dev.off()
graphics.off()