NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
#str(NEI)
#unique(NEI$type)
#unique(NEI$year)
typ = unique(NEI$type)
yrs = unique(NEI$year)
NEI$year = factor(NEI$year,levels=yrs)
NEI$type = factor(NEI$type,levels=typ)
#str(NEI)
scc = unique(NEI$SCC)
#head(scc)
NEI$SCC = factor(NEI$SCC,levels=scc)
#length(scc)
fp = unique(NEI$fips)
#length(fp)
NEI$fips = factor(NEI$fips,levels=fp)
#str(NEI)

compare_mv = which(NEI$type=="ON-ROAD" & (NEI$fips == "24510" | NEI$fips == "06037"))
compare_mv_data = NEI[compare_mv,]

compare_mv_agg = aggregate(Emissions~year+fips,data=compare_mv_data,FUN=sum)
ggplot(compare_mv_agg,aes(year,Emissions,fill=year))+geom_bar(stat="identity")+facet_wrap(~fips)
